name: CICD

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }} 

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle without test
      run: ./gradlew build -x test

    - name: Run tests for sonar-alm-client
      run: |
        ./gradlew :server:sonar-alm-client:test

    - name: Start SonarQube server
      run: |
          echo "Starting SonarQube Scanner..."
          cd sonar-application/build/distributions
          ls -R
          unzip sonar-application-25.1-SNAPSHOT.zip
          echo "ELOUAN TEST"
          ls -R
          bin/linux-x86-64/sonar.sh start
